<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Graphviz2Visio.Core\Graphviz2Visio.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="..\..\template\base-easy.vsdx"
                      Link="Templates\base-easy.vsdx"
                      LogicalName="Graphviz2Visio.Vsdx.Templates.base-easy.vsdx" />
  </ItemGroup>
</Project>
